[package]
name = "code-squirrel"
version = "0.1.0"
authors = ["James Elford <james.p.elford@gmail.com>"]

[dependencies]
clap = "2.26"
error-chain = "0.11"
futures = "0.1"
ignore = "0.2"
notify = "4.0"
ring = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempdir = "0.3"